# This file was generated by GoReleaser. DO NOT EDIT.
cask "wspace" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "3787ccc2eac67465e316d4258a644b3b1aa25d14b497039db8b63efb6fb63985"
      url "https://github.com/kivoradigital/wspace/releases/download/v#{version}/wspace_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4c3b9900710a1b097962bf90d95e24f9f3cc4e8deee1af46f63ca3510dbe21ce"
      url "https://github.com/kivoradigital/wspace/releases/download/v#{version}/wspace_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "038445eec1784c43a81af0e5116ef071b54ea0e9fd474e33a6de72bcded393ca"
      url "https://github.com/kivoradigital/wspace/releases/download/v#{version}/wspace_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c7fdee78b542ee75f367cd5e6d88cc93403fe9097fce5fd9e09c947644dc3e9a"
      url "https://github.com/kivoradigital/wspace/releases/download/v#{version}/wspace_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wspace"
  desc "Multi-repository git worktree workspaces (CLI, MCP server and RPC engine)."
  homepage "https://github.com/kivoradigital/wspace"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wspace"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wspace"]
    end
  end

  # No zap stanza required
end
