# This file was generated by GoReleaser. DO NOT EDIT.
cask "wspace" do
  version "0.2.4"

  on_macos do
    on_arm do
      sha256 "c7b88bd68a92246c118e5555c0649da800452f5be4066b38d5e8c5386678bf8c"
      url "https://github.com/kivoradigital/wspace/releases/download/v#{version}/wspace_#{version}_macos_arm64.tar.gz"
    end
    on_intel do
      sha256 "aafe9a97b37b58b5567185c82f9fb55758ac83b0e307db5f973ed7c19ec71d4f"
      url "https://github.com/kivoradigital/wspace/releases/download/v#{version}/wspace_#{version}_macos_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "eb23009f3930f98cb22c969e4865fd61ab9e3217c787038192c2dbb063ccc184"
      url "https://github.com/kivoradigital/wspace/releases/download/v#{version}/wspace_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6badf73d9d0556de9e2aae795c83eacfb1808dd853ada0e0c63faf70256461c9"
      url "https://github.com/kivoradigital/wspace/releases/download/v#{version}/wspace_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wspace"
  desc "Multi-repository git worktree workspaces (CLI, MCP server and RPC engine)."
  homepage "https://github.com/kivoradigital/wspace"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wspace"

  # No zap stanza required
end
