# This file was generated by GoReleaser. DO NOT EDIT.
cask "wspace" do
  version "0.2.2"

  on_macos do
    on_arm do
      sha256 "516cc729353d2a266ce41d1fa0aa930866025e1f65b5d11fdd0229aedd0b24e0"
      url "https://github.com/kivoradigital/wspace/releases/download/v#{version}/wspace_#{version}_macos_arm64.tar.gz"
    end
    on_intel do
      sha256 "88e4e82d9c4a08b47f218daa0b33d4b73b5699d4c2ba71f8014511f865f55a06"
      url "https://github.com/kivoradigital/wspace/releases/download/v#{version}/wspace_#{version}_macos_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3131925ec63186866372130edf25b83a4680ec96163012f8857c2a4fb67d7e3f"
      url "https://github.com/kivoradigital/wspace/releases/download/v#{version}/wspace_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "56a82ba9bb382bd5c862c7794ce6ba53c7536884ad5f3222baf893353f15f57b"
      url "https://github.com/kivoradigital/wspace/releases/download/v#{version}/wspace_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wspace"
  desc "Multi-repository git worktree workspaces (CLI, MCP server and RPC engine)."
  homepage "https://github.com/kivoradigital/wspace"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wspace"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wspace"]
    end
  end

  # No zap stanza required
end
